### ISSUE TITLE
request for XiaomiBTLESens module

### ISSUE THREAD

**Issue by VinceMasuka** [dominikkarall/fhem_pythonbinding#5]
Hidey ho!

Any chance for the popular XiaomiBTLESens module support?
(it's like predestinated for pythonbinding of sorts)

Thanks!

Regards
Vince

**Comment by dominikkarall** [comment]
Hi,

shouldn't be a problem to integrate it. I can do the integration of the plant sensor with miflora (https://pypi.org/project/miflora/) as that library exists already. There is also another python library for the temperature sensor.

Do you have a plant sensor to test with? Unfortunately my plant sensor doesn't work any more.

**Comment by VinceMasuka** [comment]
Yes, I do have a whole bunch of them, ready for testing... Just let me know I may be of service.

**Comment by dominikkarall** [comment]
I just committed an absolutely untested version:
https://github.com/dominikkarall/fhem_pythonbinding/blob/master/FHEM/bindings/python/lib/miflora/README.md

Can you please test it and provide me logs if errors occure?

**Comment by VinceMasuka** [comment]
Errors occur as follows...

This is the FHEM list of the teseted device (/sensor):
```
Internals:
   CFGFN      
   DEF        miflora C4:7C:8D:66:B0:EF
   FUUID      5fa7bcea-f33f-e5c5-3b29-c89314814ce43df0
   IODev      bndAPi
   NAME       miAloe
   NR         547
   PYTHONTYPE miflora
   STATE      Failed to load module miflora: Traceback (most recent call last):
  File "/home/pi/fhem_pythonbinding/FHEM/bindings/python/lib/fhem_pythonbinding.py", line 189, in _onMessage
    module_object = importlib.import_module(pymodule)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lib.miflora'

   TYPE       PythonModule
   READINGS:
     2020-11-08 10:39:56   state           Failed to load module miflora: Traceback (most recent call last):
  File "/home/pi/fhem_pythonbinding/FHEM/bindings/python/lib/fhem_pythonbinding.py", line 189, in _onMessage
    module_object = importlib.import_module(pymodule)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lib.miflora'

   args:
     miAloe
     PythonModule
     miflora
     C4:7C:8D:66:B0:EF
   argsh:
Attributes:
   IODev      bndAPi
```

The log file
`./log/PythonBinding-%Y-%m-%d.log`
repeatedly gets filled with this block of text:
`SyntaxError: invalid syntax
Traceback (most recent call last):
  File "FHEM/bindings/python/pythonbinding.py", line 3, in <module>
    import lib.fhem_pythonbinding as fpb
  File "/opt/fhem/FHEM/bindings/python/lib/fhem_pythonbinding.py", line 200
    errorMsg = f"Function execution >{fct_timeout}s, cancelled: {hash['NAME']} Define"`

Side info:

- IODev "bndAPi" (remote peer) binding is already working for some eq3bt thermostats and working flawlessly so far.


The
`ModuleNotFoundError: No module named 'lib.miflora'`
stated above looks like it's missing some library?

**Comment by dominikkarall** [comment]
Ah, you didn't update the remote peer. Please do a `git pull` in the fhem_pythonbinding directory on the remote peer. After that restart it with `sudo systemctl restart fhem_pythonbinding`. You don't need to do anything in fhem.

...I need to implement a peer update functionality...

**Comment by VinceMasuka** [comment]
Right. After "git pull" and restarting the "fhem_pythonbinding" on remote peer we see an update process on the device within FHEM resulting in this device list, showing some fresh error:
```
Internals:
   CFGFN      
   DEF        miflora C4:7C:8D:66:B0:EF
   FUUID      5fa7bcea-f33f-e5c5-3b29-c89314814ce43df0
   IODev      bndAPi
   NAME       miAloe
   NR         547
   PYTHONTYPE miflora
   STATE      Failed to execute function Define: Traceback (most recent call last):
  File "/home/pi/fhem_pythonbinding/FHEM/bindings/python/lib/fhem_pythonbinding.py", line 236, in _onMessage
    ret = await asyncio.wait_for(func(hash, hash['args'], hash['argsh']), fct_timeout)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/home/pi/fhem_pythonbinding/FHEM/bindings/python/lib/miflora/miflora.py", line 35, in Define
    await utils.handle_define_attr(self._attr_list, self, hash)
  File "/home/pi/fhem_pythonbinding/FHEM/bindings/python/lib/utils.py", line 75, in handle_define_attr
    setattr(obj, "_attr_" + attr, convert2format(curr_val, attr_list[attr]['format']))
KeyError: 'format'

   TYPE       PythonModule
   READINGS:
     2020-11-08 12:41:22   state           Failed to execute function Define: Traceback (most recent call last):
  File "/home/pi/fhem_pythonbinding/FHEM/bindings/python/lib/fhem_pythonbinding.py", line 236, in _onMessage
    ret = await asyncio.wait_for(func(hash, hash['args'], hash['argsh']), fct_timeout)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/home/pi/fhem_pythonbinding/FHEM/bindings/python/lib/miflora/miflora.py", line 35, in Define
    await utils.handle_define_attr(self._attr_list, self, hash)
  File "/home/pi/fhem_pythonbinding/FHEM/bindings/python/lib/utils.py", line 75, in handle_define_attr
    setattr(obj, "_attr_" + attr, convert2format(curr_val, attr_list[attr]['format']))
KeyError: 'format'

   args:
     miAloe
     PythonModule
     miflora
     C4:7C:8D:66:B0:EF
   argsh:
Attributes:
   IODev      bndAPi
   userattr   hci_device update_interval
```

Whereas log file...
```
./log/PythonBinding-%Y-%m-%d.log
```
...tells nothing new:
```
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "FHEM/bindings/python/pythonbinding.py", line 3, in <module>
    import lib.fhem_pythonbinding as fpb
  File "/opt/fhem/FHEM/bindings/python/lib/fhem_pythonbinding.py", line 200
    errorMsg = f"Function execution >{fct_timeout}s, cancelled: {hash['NAME']} Define"
```

**Comment by dominikkarall** [comment]
Thanks, please do one more test after `git pull` on remote peer.

**Comment by VinceMasuka** [comment]
As
```
git pull
```
came up with no news I just saw, that the FHEM instance found some new files, too. That's why I did a quick
```
update
```
```
shutdown restart
```
in FHEM, too (I guess that somehow makes sense).

And look what we have here:
```
Internals:
   DEF        miflora C4:7C:8D:66:B0:EF
   FUUID      5fa82801-f33f-e5c5-29e0-79a1cf54407afcba
   FVERSION   10_PythonModule.pm:0.182830/2019-01-16
   IODev      bndAPi
   MAC        C4:7C:8D:66:B0:EF
   NAME       miAloe
   NR         407
   PYTHONTYPE miflora
   STATE      online
   TYPE       PythonModule
   READINGS:
     2020-11-08 18:19:25   battery         100
     2020-11-08 18:19:25   conductivity    38
     2020-11-08 18:19:25   firmware        3.2.1
     2020-11-08 18:19:25   light           27
     2020-11-08 18:19:25   moisture        8
     2020-11-08 18:19:25   name            Flower care
     2020-11-08 18:19:25   presence        online
     2020-11-08 18:19:25   state           online
     2020-11-08 18:19:25   temperature     21.7
   args:
     miAloe
     PythonModule
     miflora
     C4:7C:8D:66:B0:EF
   argsh:
Attributes:
   IODev      bndAPi
   userattr   hci_device update_interval
```

So I'm curious:
As it does not update it's readings since device is online and there is this (yet unset) attribute:
```
attr miAloe userattr hci_device update_interval
```
Will that be the update interval in seconds, maybe minutes?
(it just does nothing, if I put some value here)

**Comment by VinceMasuka** [comment]
PS:
I had a quick glace at the corresponding, yet oldfashioned, currently disabled module "XiaomiBTLESens"....
```
Internals:
   BTMAC      C4:7C:8D:66:B0:EF
   DEF        C4:7C:8D:66:B0:EF
   FUUID      5d7c9840-f33f-e5c5-fa06-5c29987cef826e45
   FVERSION   74_XiaomiBTLESens.pm:v3.0.0-s22474/2020-07-26
   INTERVAL   7200
   NAME       plantAloe
   NOTIFYDEV  global,plantAloe
   NR         172
   NTFY_ORDER 50-plantAloe
   STATE      disabled
   TYPE       XiaomiBTLESens
   VERSION    v3.0.0
   loglevel   4
   READINGS:
     2020-11-08 14:33:34   batteryPercent  100
     2020-11-08 14:33:34   batteryState    ok
     2020-11-08 14:33:51   fertility       32
     2020-11-08 14:33:34   firmware        3.2.1
bash
     2020-11-08 14:33:51   lux             955
     2020-11-08 14:33:51   moisture        8
     2020-11-08 18:39:49   state           disabled
     2020-11-08 14:33:51   temperature     25.9
   helper:
     CallBattery 0
     CallSensDataCounter 0
     updateTimeCallBattery 0
Attributes:
   disable    1
   interval   7200
   maxFertility 1000
   maxLux     70000
   maxMoisture 50
   maxTemp    35
   minFertility 300
   minLux     3000
   minMoisture 7
   minTemp    8
   model      flowerSens
   room       XiaomiBTLESens
   sshHost    pi@api
   verbose    2
```
...where we find an internal called "INTERVAL" what currently comes with an value of "7200". As this interval just hit every 2 hours, I guess your interval would be in seconds, too?

PPS:
By the time of writing this, I just saw that your modules already updates...
```
Internals:
   DEF        miflora C4:7C:8D:66:B0:EF
   FUUID      5fa82801-f33f-e5c5-29e0-79a1cf54407afcba
   FVERSION   10_PythonModule.pm:0.182830/2019-01-16
   IODev      bndAPi
   MAC        C4:7C:8D:66:B0:EF
   NAME       miAloe
   NR         407
   PYTHONTYPE miflora
   STATE      online
   TYPE       PythonModule
   READINGS:
     2020-11-08 18:19:25   battery         100
     2020-11-08 18:39:35   conductivity    37
     2020-11-08 18:19:25   firmware        3.2.1
     2020-11-08 18:39:35   light           118
     2020-11-08 18:19:25   moisture        8
     2020-11-08 18:19:25   name            Flower care
     2020-11-08 18:19:25   presence        online
     2020-11-08 18:19:25   state           online
     2020-11-08 18:19:25   temperature     21.7
   args:
     miAloe
     PythonModule
     miflora
     C4:7C:8D:66:B0:EF
   argsh:
Attributes:
   IODev      bndAPi
   userattr   hci_device update_interval
```
[please see reading "conductivity" (fertility in the old module) and "light" (formerly know as lux)]
That's 20 minutes and 10 seconds away from last update... So there is an interval of about 1200 already?

**Comment by dominikkarall** [comment]
Great!
conductivity and light are the names which are defined in the miflora library. I tend to keep the standard from the library.

Interval is indeed 1200s default. You can set the interval with `update_interval` attribute in seconds. I have no reading/internal yet where the change is visible.
`hci_device` can be used to set a bluetooth adapter other than `hci0`.

Let me know if you want some further functions included beside the interval internal.

**Comment by dominikkarall** [comment]
I updated the module to include an `update_interval` reading.

Furthermore I added `mitemp` module as well. If you have temp/humidity BLE sensors, you might want to test that one as well.

I'm going to close this issue, please open a new one if you want further functionality to be included. Many thanks for your testing!
